language: php

sudo: required

install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose


script:
  - ls -lah
  - docker-compose up -d
  - docker exec -it symfony_php composer install
  - docker exec -it symfony_php vendor/bin/phpunit