sudo: required

services:
  - docker

script:
  - docker run -it -v $PWD:/app -w /app letsbonus/php-dev:7.0 composer install -n
  - docker run -it -v $PWD:/app -w /app letsbonus/php-dev:7.0 vendor/bin/phpunit
