version: '2'

services:
  code:
    build: etc/build/dev/code
    container_name: symfony_code
    volumes:
      - ./:/app

  nginx:
    build: etc/build/dev/nginx
    container_name: symfony_nginx
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
        - code
    volumes:
      - ./var/logs/nginx:/var/log/nginx

  php:
    image: jorge07/php7-xdebug-ssh
    container_name: symfony_php
    volumes:
        - ~/.ssh:/root/ssh
    volumes_from:
        - code
    ports:
      - "9000:9000"
      - "2222:22"
    links:
      - code
      - redis

  redis:
    image: redis:3.0.7-alpine
    ports:
      - 6379:6379
    container_name: symfony_redis

  elk:
    image: willdurand/elk
    container_name: symfony_elk
    ports:
        - 81:80
    volumes:
        - ./etc/build/dev/elk/logstash:/etc/logstash
        - ./etc/build/dev/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - code
